### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by mumuyeye** [hiyouga/FastEdit#23]
################################
#                              #
#  Retrieving hyperparameters  #
#                              #
################################
Traceback (most recent call last):
  File "/home/lyn/miniconda3/envs/fastedit/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lyn/miniconda3/envs/fastedit/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/lyn/FastEdit/fastedit/editor.py", line 79, in <module>
    fire.Fire(test_rome)
  File "/home/lyn/miniconda3/envs/fastedit/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/lyn/miniconda3/envs/fastedit/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/lyn/miniconda3/envs/fastedit/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/lyn/FastEdit/fastedit/editor.py", line 46, in test_rome
    hparams = ROMEHyperParams.from_name(config)
  File "/home/lyn/FastEdit/fastedit/rome/rome_hparams.py", line 97, in from_name
    raise NotImplementedError
NotImplementedError

想请问一下运行以下命令时报错是怎么回事啊，我将模型已经下载到了本地：
CUDA_VISIBLE_DEVICES=0 python -m fastedit.editor \
    --data data/example.json \
    --model /home/lyn/gpt2-xl \
    --config gpt2-xl \
    --template default

**Comment by hiyouga** [comment]
GPT2-XL 的 config 还没有实现，下周内我们会增加这个模型

**Comment by mumuyeye** [comment]
特别感谢！


&nbsp;


丅
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月17日(星期天) 下午5:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hiyouga/FastEdit] 运行时报错 (Issue #23)





 
GPT2-XL 的 config 还没有实现，下周内我们会增加这个模型
