### ISSUE TITLE
请教如何配置config？

### ISSUE THREAD

**Issue by songbaiTalk** [hiyouga/FastEdit#6]
请问config和template指定有说明吗，我直接用这样的方式指定报错：
CUDA_VISIBLE_DEVICES=0 python -m fastedit.editor \
    --data data/example.json \
    --model baichuan-inc/Baichuan-7B \
    --config Baichuan-7B \
    --template default

Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/SageMaker/FastEdit/fastedit/editor.py", line 71, in <module>
    fire.Fire(test_rome)
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/ec2-user/SageMaker/conda/chatglm_etuning/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/ec2-user/SageMaker/FastEdit/fastedit/editor.py", line 43, in test_rome
    hparams = ROMEHyperParams.from_name(config)
  File "/home/ec2-user/SageMaker/FastEdit/fastedit/rome/rome_hparams.py", line 91, in from_name
    raise NotImplementedError
NotImplementedError

**Comment by hiyouga** [comment]
使用 --config llama-7b 即可
